[versions]
agp = "8.5.1"
bson = "4.11.1"
glide = "4.16.0"
gson = "2.13.1"
jakartaMailApi = "2.1.3"
jbcrypt = "0.4"
json = "20250517"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.9.0"
constraintlayout = "2.2.1"
mongodbDriverSync = "4.11.1"
okhttpVersion = "4.10.0"
lombok = "1.18.38"
retrofit = "2.9.0"

[libraries]
bson = { module = "org.mongodb:bson", version.ref = "bson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jakarta-mail-api = { module = "jakarta.mail:jakarta.mail-api", version.ref = "jakartaMailApi" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodbDriverSync" }
okhttp-v4100 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

